name: Deploy to Bucket
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_BUCKET: "gs://hacktime-site"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v3

    - run: rm -rf infra/

    - name: 'GCP Auth'
    uses: 'google-github-actions/auth@v0'
    with:
      credentials_json: '${{ secrets.GCS_SA_CREDS }}'
      service_account: 'hacksite-gcs-deploy@hacktime-site.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Gsutil rsync to Bucket'
      run: gsutil rsync -r ./* $GCP_BUCKET
